### PR TITLE
BWFirstReview

### PR DESCRIPTION
**Pull request by brendonw1**
Poorly named the branch, didn’t properly anticipate when I downloaded
it.  I looked things over for the first time and restructured some code
and added some specifics based on my thoughts.  Hope it’s not too
different.

### CODE REVIEW

**Comment by dlevenstein** [comment]
looks good!

git success

**Comment by brendonw1** [comment]
Take a look at the code sometime it's a bit different from yours, hope it's
oK.

Also, I used fullfile, it is an OS-independent way of making paths that
will be more generalizable (basically inserts slashes in the proper
direction for the OS you're in).

**Comment by dlevenstein** [comment]
Glanced through, looks good. Hadn’t known about fullfile - nice.  Will incorporate that into how I write my code in the future.
TAing today but I’ll get a chance to look through in more detail soon.
Dan

**Comment by brendonw1** [comment]
No worries/rush, just felt bad I rearranged some basics and wanted to make
sure you're OK.

**Comment by dlevenstein** [comment]
Definitely - feel free to rearrange as necessary.  I’m sure we’ll go through multiple iterations of how things are structured etc, as well as the details of the algorithm.

**Pull request merged**
