### PR TITLE
Should work now

### PR DESCRIPTION
**Pull request by brendonw1**

### CODE REVIEW

**Comment by dlevenstein** [comment]
hm.  it says there are "conflicts that must be resolved"... trying to figure out how to do that

**Comment by dlevenstein** [comment]
Had to "update from master" on the branch before merging the pull request - I think it's because you had changed a line of code on the branch and I had in parallel changed the same line on the master... 
In the future I'll work on a branch instead of working on the master, which I think is what I'm supposed to do anyway.

**Comment by brendonw1** [comment]
Cool, sounds like we're getting there

**Comment by brendonw1** [comment]
My next step is to get the dataset in line.
Anything higher priority than that?
Oh and I'm also of course slowly processing the c3po data which will be
useful.

But it's gonna have to be next week after my surgery... at least I think I
won't get to much of it before that.

**Comment by dlevenstein** [comment]
yeah.  it's a learning process :p 

Now that the master is updated, I merged the master onto "pick good SW/theta channel" branch I've been working on - seems like proper git

**Comment by dlevenstein** [comment]
nothing higher priority than that - next week is AOK - I'll aim to have a working draft of the full scoring process ready by then. Then we can run it on a dataset and then go through the scoring and identify all the places it's crap and figure out what we can change to uncrap them. Sound like a good plan of attack?

**Comment by brendonw1** [comment]
Great plan of attack

**Pull request merged**
