### PR TITLE
comments in EMG functionality

### PR DESCRIPTION
**Pull request by dlevenstein**
…

### CODE REVIEW

**Comment by brendonw1** [comment]
I might finish EMGCorr tomorrow.
If I get time I will.  I have no idea how long this antibody business
takes.  It seems like it'll just take a couple hours total, but it's my
first time and i could see it eating into lots of the day.

How do you want me to output and/or save?  Should I save the same kind of
.mat?  Should I also output to the main master function?

**Comment by dlevenstein** [comment]
I think save to .mat and output to master function.

We can make saving to .mat an option, so that if people don’t care about making the .mat they don’t have to, or if we’re running a bunch of tests or something but don’t want it to write over old .mat.  But for our purposes generally I think we’ll want to have the EMG just in case we want to look at it later for more analyses like looking what happens at REM->NREM fuzzy transition etc.

**Comment by brendonw1** [comment]
By the way I did a pull request last night.  I assume you got it, but let
me know if you didn't.  Just want to make sure the system fully works

**Comment by dlevenstein** [comment]
Hm - I didn't get an email and it's not showing up as an open pull request on the github page

**Comment by brendonw1** [comment]
You got it now, right?

**Comment by dlevenstein** [comment]
Yup, got it!

**Pull request merged**
